### ISSUE TITLE
autoconfig

### ISSUE THREAD

**Issue by mmahmoudian** [aitjcize/Gummi#11]
I was about to install Gummi on my Mac (OSX Yosemite 10.10.1) and I followed the instructions in the INSTALL file:
```zsh
➜  Gummi-master  ./configure; make; make install
zsh: no such file or directory: ./configure
```

so I tried to run ./configure.ac  and got this error:
```zsh
➜  Gummi-master  ./configure.ac 
./configure.ac: line 4: syntax error near unexpected token `2.65'
./configure.ac: line 4: `AC_PREREQ(2.65)'
```
I have these already installed via macport:
* autoconf @2.69_2 (active)
* autoconf213 @2.13_1 (active)

I also tried to change the required autoconfig version to 2.69 and 2.69_2 from the ./configure.ac file but I got the same error.

Perhaps the INSTALL file and the ./configure.ac  should be updated or do you suggest any workaround?

**Comment by alexf91** [comment]
You are right, the INSTALL file is not up to date

Execute autogen.sh first, this should create the configure script.

**Comment by aitjcize** [comment]
Execute `./autogetn.sh' to generate the `configure' script.
You may need to modify the `AM_VERSION' variable in `autogen.sh` to match the automake version on your system.

**Comment by greg121** [comment]
Same problem here. After executing autogen.sh:

~/gummi$ bash autogen.sh 
+ '[' x '!=' x ']'
+ aclocal-1.14
autogen.sh: line 11: aclocal-1.14: command not found
+ autoheader
autogen.sh: line 12: autoheader: command not found
+ AUTOMAKE=automake-1.14
+ libtoolize -c --automake
autogen.sh: line 13: libtoolize: command not found
+ automake-1.14 --add-missing --copy --include-deps
autogen.sh: line 14: automake-1.14: command not found
+ autoconf
autogen.sh: line 15: autoconf: command not found
+ cp -f /usr/share/automake-1.14/mkinstalldirs .
cp: cannot stat ‘/usr/share/automake-1.14/mkinstalldirs’: No such file or directory
+ rm -rf autom4te.cache

**Comment by aitjcize** [comment]
make sure you have autoconf and automake in your system
