### ISSUE TITLE
Cannot update in <1 second

### ISSUE THREAD

**Issue by mermerico** [aitjcize/Gummi#15]
I have a pretty slow laptop, but even on this machine, recompiling a document usually takes less than a second. That means that the biggest barrier to updating is the GUI limit of 1 second. On my machine, I've gone into the settings file and changed the update rate to 0.1 seconds, and it works great! It would be nice for other users if this functionality was exposed.

**Comment by aitjcize** [comment]
Actually the timer is parsed as a integer so the update time is essentially 0 seconds, i.e. it updates immediately after you make changes. I think I'll allow the GUI to set compile time to 0 seconds, that ways it will work like you described.

**Comment by mermerico** [comment]
Ah, that makes sense. Thanks!
