### ISSUE TITLE
% !TEX root = root.tex

### ISSUE THREAD

**Issue by 85pando** [aitjcize/Gummi#4]
Gummi is not able to cope with the comment ```% !TEX root = tutorial.tex``` which can normaly be used to compile from "internal tex files", like a file that is used via ```\input{internal.tex}``` in another file.

For huge documents this would really be usefull, as you can then compartmentalize the document in multiple small files.

**Comment by aitjcize** [comment]
Can you give an example on how you would like this to work? Do you mean like open a file say `chap1.tex` with a line '% !TEX root = tutorial.tex' in the file, and Gummi should automatically compile tutorial.tex and display it? (instead of trying to comiple chap1.tex and display it)

**Comment by 85pando** [comment]
Yeah exactly, when editing the inputed file, the parent should be compiled.

Excelltn. Many thanks!

**Comment by aitjcize** [comment]
np, start the project if you like it :P
