### ISSUE TITLE
Packages

### ISSUE THREAD

**Issue by plsng** [aitjcize/Gummi#8]
Are there any plans to provide updated packages of Gummi for the common distros? It seems the original project is completely abandoned now anyway as the site is dead.

**Comment by aitjcize** [comment]
There is a Ubuntu PPA available here: https://launchpad.net/~gummi/+archive/ubuntu/gummi
Also it's available on AUR: https://aur.archlinux.org/packages/gummi-gtk3-git/

**Comment by plsng** [comment]
Thanks! Will you provide an OBS repo as well?

**Comment by aitjcize** [comment]
I don't use OpenSUSE myself. Would you like to help maintaining it?

**Comment by plsng** [comment]
Unfortunately I don't really have any experience with maintaining packages.
